name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.17", "1.16", "1.15", "1.14"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Install dependencies
        run: |
          go get -u golang.org/x/lint/golint@latest
          go get -u github.com/mattn/goveralls@v0.0.9

      - name: Lint
        run: |
          go vet ./...
          golint -set_exit_status ./...

      - name: Test
        run: |
          go test -v -race -covermode=atomic -coverprofile=profile.cov ./...

      - name: Coverage
        run: |
          goveralls -coverprofile=profile.cov -service=github -parallel -flagname="go-${{ matrix.go }}"
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
